---
- name: add syslog server
  hosts: all
  strategy: free
  tasks:
  - name: add syslog server address
    lineinfile:
      path: /etc/rsyslog.d/50-default.conf
      line: '*.* @192.168.0.133:515'
  - name: restart systemd
    ansible.builtin.service:
      name: rsyslog
      state: restarted
