---
- name: add syslog server
  hosts: all
  strategy: free
  tasks:
  - name: add syslog server address
    lineinfile:
      path: /etc/rsyslog.d/50-default.conf
      line: '*.* @{{ remote_ssyslog_server }}:{{ remote_ssyslog_port }}'
  - name: restart systemd
    ansible.builtin.service:
    name: rsyslog
    state: restarted
