---
- name: Create VMagent system group
  group:
    name: "{{ vmagent_system_group }}"
    state: present
    system: true
  when: vmagent_system_group != "root"

- name: Create VMagent system user
  user:
    name: "{{ vmagent_system_user }}"
    groups: "{{ vmagent_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: vmagent_system_user != "root"

- name: Ensure existense of /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Delete existing VMagent version if it's different.
  file:
    path: /usr/local/bin/vmagent-prod
    state: absent
  when:
  - vmagent_is_installed.stat.exists | bool
  - vmagent_version not in vmagent_current_version.stdout

- name: Copy vmagent binary to target host
  notify: Restart VMagent service
  copy:
    src: "{{ vmagent_src_file_path }}"
    dest: /usr/local/bin/vmagent-prod
    mode: 0751
    owner: "{{ vmagent_system_user }}"
    group: "{{ vmagent_system_group }}"
  when:
  - not ansible_check_mode
  - not vmagent_is_installed.stat.exists or vmagent_version not in vmagent_current_version.stdout